version: "3.9"

services:
  traefik:
    image: traefik:v2.9
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"

    healthcheck:
      test: ["CMD", "wget", "http://localhost:8082/ping", "--spider"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.example.com`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc/traefik.yml:/etc/traefik/traefik.yml
      - ./etc/dynamic.toml:/etc/traefik/dynamic.toml
      - ./etc/traefik/ssl/:/ssl-certs/

    networks:
      - traefik-network

    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
        protocol: tcp
      - target: 443
        published: 443
        mode: host
        protocol: udp

networks:
  traefik-network:
    external: true