certificatesResolvers:
  default:
    acme:
      email: 나의이메일@이메일.com
      storage: /ssl-certs/acme.json
      httpChallenge:
        entryPoint: web

global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: :443
    http:
      tls:
        certResolver: default
    http3:
      advertisedPort: 443
  
  ping:
    address: :8082

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    network: "traefik-network"
    watch: true
  file:
    filename: /etc/traefik/dynamic.toml
    watch: true

metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    headerLabels:
      useragent: User-Agent

experimental:
  http3: true